---
title: "Rで学ぶ計量経済学と機械学習 9<br> <br> 計量経済学5：差の差法、合成コントロール法（未定稿)"
author: "安藤道人（立教大学）　三田匡能 (株式会社 GA technologies)"
date: "`r Sys.Date()`"
output:
 html_document:
    css : R_style.css
    self_contained: true   # 画像などの埋め込み 
    #theme: cosmo
    highlight: haddock     # Rスクリプトのハイライト形式
    #code_folding: 'hide'  # Rコードの折りたたみ表示を設定
    toc: true
    toc_depth: 2           # 見出しの表示とその深さを指定
    toc_float: true        # 見出しを横に表示し続ける
    number_sections: true # 見出しごとに番号を振る
    # df_print: paged        # head()の出力をnotebook的なものに（tibbleと相性良）
    latex_engine: xelatex  # zxjatypeパッケージを使用するために変更
    fig_height: 4          # 画像サイズのデフォルトを設定
    fig_width: 6           # 画像サイズのデフォルトを設定
    dev: png
classoption: xelatex,ja=standard
editor_options: 
  chunk_output_type: console
---


```{r include = FALSE}
knitr::opts_chunk$set(fig.align = 'center', message = F, warning = F)
```

# データの生成

```{r}
# 事前準備 --------------------
# パッケージの読み込み
library(tidyverse)
library(plm)
library(stargazer)
# 乱数の種を固定
set.seed(0)

# データの生成 ----------------
n <- 10000
# 能力は0から100まで均等に分布
ability <- runif(n, min = 0, max = 100)

# IDとabilityをデータフレームに格納する
df <- tibble(ID = 1:n, ability)

# 1年目

## year = 0を加える
df0 <- df %>% mutate(year = 0)

##　職業訓練フラグ
##　一年目は誰も職業訓練をうけない
df0 <- df0 %>% mutate(training = 0)

#所得 incomeを加える
df0 <- df0 %>% mutate(income = 200 + 10*ability + rnorm(n, mean = 0, sd = 50))

# 2年目

## year = 1　を加える
df1 <- df %>% mutate(year = 1)

## 職業訓練フラグ
## 条件：能力を部分的に反映した適正試験が 180 点以上であれば職業訓練を受けられる
## 10%くらいが該当するように恣意的に設定
## abilityとscoreの関係は非線形なものとする
## 今回もmutate()とcase_when()を使用して作成

#適正試験の点数 score
df1 <- df1 %>% mutate(score = 30 * log10(ability) + rnorm(n, mean = 115, sd = 10))
#職業訓練ダミー training (score 180点以上=1)
df1 <- df1 %>% mutate(training = case_when(score >= 180 ~ 1, TRUE ~ 0))
#所得 income: 年ショックとして100も追加
df1 <- df1 %>% mutate(income = 200 + 10*ability + 500*training + rnorm(n, mean = 100, sd = 50))

# 1年目と2年目をくっつける。
df_binded <- bind_rows(df0, df1)

# panelとして認識
df_panel <- pdata.frame(df_binded, index = c("ID", "year")) # 個体=firm、時間=yearと認識させたdf
```

# 差の差推定

```{r}
# regression

# pooled OLS
pool_lm <- lm(income ~ training, data = df_panel)
summary(pool_lm)

pool_plm <- plm(income ~ training, data = df_panel, model = "pooling")
summary(pool_plm)

# DID with one-way FE model
DID_plm1 <- plm(income ~ training + training*year, data = df_panel, model = "within")
summary(DID_plm1)

# DID with two-way FE model
DID_plm2 <- plm(income ~ training, data = df_panel, model = "within", effect = "twoways")
summary(DID_plm2)

stargazer(pool_lm, pool_plm, DID_plm1, DID_plm2, type = "text", digits = 3, df = FALSE,
          column.labels = c("Pooled(lm)","Pooled(plm)","DID(onewayFE)","DID(twowayFE)"),
          model.names = F, model.numbers = F)
```


# 参考文献

安藤道人「計量経済学２」あるいは「計量経済特論２」の「差の差法」の[講義資料](https://sites.google.com/site/michihito7ando/lectures)
